# Generated by Django 5.0.4 on 2024-04-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=256, verbose_name='Учреждение')),
                ('region', models.CharField(max_length=256, verbose_name='Регион')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
                ('year', models.IntegerField(default=0, verbose_name='Год')),
                ('budget_amount', models.IntegerField(default=0, verbose_name='Размер иного межбюджетного трансферта')),
            ],
        ),
    ]
